version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: "@babel/parser"
    versions:
    - 7.13.4
  - dependency-name: mocha-eslint
    versions:
    - 6.0.0
